### ISSUE TITLE
l10n error

### ISSUE THREAD

**Issue by dixonge** [digitalcraftsman/hugo-icarus-theme#1]
Getting this error for every post when I run `hugo server`

`ERROR: 2015/11/16 template: theme/partials/pagination.html:10:27: executing "theme/partials/pagination.html" at <.Site.l10n.paginatio...>: l10n is not a field of struct type *hugolib.SiteInfo in theme/partials/pagination.html`

**Comment by digitalcraftsman** [comment]
Thanks for reporting this issue. Now it should work as expected.
