### ISSUE TITLE
Mastodon link in bio?

### ISSUE THREAD

**Issue by matthiasbeyer** [digitalcraftsman/hugo-icarus-theme#103]
Hi,

would be cool to have a mastodon link in the bio section.

:smile: :+1: thanks for developing this theme, I love it!

**Comment by grinsted** [comment]
You can add it yourself by making a custom /layouts/partials/social.html file. 

I did it here for email and phone options: https://github.com/grinsted/src.glaciology.net/blob/master/layouts/partials/social.html

see also this PR: #102

**Comment by matthiasbeyer** [comment]
Nice, thanks!
