### ISSUE TITLE
LICENSE.md should list ZHANG Ruipeng's name (instead of Tommy Chen's?)

### ISSUE THREAD

**Issue by anthonyfok** [digitalcraftsman/hugo-icarus-theme#14]
See Pull Request ppoffice/hexo-theme-icarus#85 for more information, though maybe we should wait until @ppoffice actually merges it or modifies LICENSE the way he likes it.

**Comment by digitalcraftsman** [comment]
Thanks for reporting this issue to us. I'll add @ppoffice's changes until he merged your Pull Request.
