### ISSUE TITLE
reflect.Value.Type error

### ISSUE THREAD

**Issue by cfjedimaster** [digitalcraftsman/hugo-icarus-theme#17]
Seeing this error repeated once for every piece of content:

ERROR: 2016/01/03 reflect: call of reflect.Value.Type on zero Value in theme/partials/widgets/recent_articles.html

**Comment by digitalcraftsman** [comment]
Hello @cfjedimaster,

thanks for reporting this issue. I created a fresh setup of the theme. The issue occurs if no post was created yet. I'll have a look.

**Comment by cfjedimaster** [comment]
I've got 25 pages already though. (By the way, I'm super new to Hugo, so I definitely could be doing things wrong.)

**Comment by digitalcraftsman** [comment]
I've updated the templates. Could you pull the latest changes and look if the error messages are still present?

**Comment by cfjedimaster** [comment]
Perfect! I also had a layout issue in the side bar, but this fixed that too so it must have been related. Thanks for the quick fix!

**Comment by digitalcraftsman** [comment]
You are welcome.
