### ISSUE TITLE
Next and Previous page links incorrect when blog hosted in sub directory

### ISSUE THREAD

**Issue by cummins-gg** [digitalcraftsman/hugo-icarus-theme#20]
Hi when hosting the blog in a sub directory i.e. http://www.domain.com/blog/ the links for the next or previous page appear to be generated incorrectly as follows: http://www.domain.com/page/2 instead of http://www.domain.com/blog/page/2

As far as I can tell all othe pages generate okay. This appears both on Hugo's webserver and once the site has been built too. 

Thanks
Peter

**Comment by digitalcraftsman** [comment]
Hello Peter,

I was able to reproduce this issue, even if the `baseurl` in the config was set correctly to `http://www.domain.com/blog/`. I'll have a look into the code.

**Comment by digitalcraftsman** [comment]
I've tested this with some of my other themes and those of other theme creators. In all test I got a 404 error. Furthermore, I tested it with the latest release of Hugo (v0.15) and the the latest developer version.

In the next step I searched for similar issues in the Hugo forum and for issues on Github regarding this issue but did not found anything. However, it seems to be an issue with Hugo itself. I'll open an issue.

**Comment by digitalcraftsman** [comment]
The mistake was that the urls of the previous- and next-button are actually relative to the domain. This means that the buttons always linked to `http://www.domain.com/page/<NUMBER>/`. By prepending the baseurl that you have defined the config file we get the expected link: `http://www.domain.com/blog/page/<NUMBER>/` (notice the added blog part).

Hugo itself generated the pages correctly, but they were just linked wrong. However, I've fixed the issue in f1ef0c692b6bd99e3db4997a19d3172bcb2758c7.

Reopen this issue if you still have problems.
Thanks.
