### ISSUE TITLE
The profile card seems to appears on wrong position

### ISSUE THREAD

**Issue by yewton** [digitalcraftsman/hugo-icarus-theme#21]
Hi,

I have noticed that the profile card pop-up is shown at too low position on every page except the index page.

I think `{{ partial "header" . }}` should be in `<div id="container">`.
Please consider to fix it.

Thanks to provide such a great theme!

**Comment by digitalcraftsman** [comment]
Hello @yewton,

thanks for opening this issue. You mean that the header partial should be placed as in one of your [last commits](https://github.com/yewton/yewton-hugo/commit/3663ffad437a266f55eb671893d87103c155864e), right?

I changed the template this way but didn't saw any difference between multiple types of pages. Would it be possible to post a screenshot for a comparison. Maybe I don't fully grasp the issue.

**Comment by yewton** [comment]
Thank you for your quick reply!

> thanks for opening this issue. You mean that the header partial should be placed as in one of you last commits, right?

Yes, this commit seems to fix the issue, but I don't know why :confounded: 

Here are the screenshots indicating the issue:

#### Profile Card on Index

![icarus-profile-index](https://cloud.githubusercontent.com/assets/363938/12377166/894a7c1e-bd56-11e5-9671-66583842c360.jpg)

#### Profile Card on other pages

![icarus-profile-other](https://cloud.githubusercontent.com/assets/363938/12377169/9076828a-bd56-11e5-8392-f2b63f21a443.jpg)

**Comment by digitalcraftsman** [comment]
Thanks for your clarification. With profile card I thought you mean the left sidebar (which resides in a template called `profile.html`). I totally forgot the profile card shown on smaller screenresolutions :smile:  

After a quick look into the source code of the original Hexo theme I saw that the profile card belongs into `<div id="container">`.

Give me a minute and I'll push a fix.

**Comment by digitalcraftsman** [comment]
The fix has been pushed. See 7c263476a6180aace74a781389cea2cacfe9ae0b.

**Comment by yewton** [comment]
Thank you for your quick and perfect job! :+1:
