### ISSUE TITLE
Question: Adding custom post types to the home page

### ISSUE THREAD

**Issue by caraya** [digitalcraftsman/hugo-icarus-theme#22]
I'm learning how to use Hugo,  I've created custom types (project and component) and am experiencing the following issues:

I can't add the new post types.  I see the the paginator code in article-list.html `{{ $paginator := .Paginate (where .Site.Pages "Type" "post") }}` but it only uses the post type and I don't know how do I incorporate types other than posts. 

Can a dev comment the code with instructions or document this? The Hugo instructions make no mention of this? 

Am I missing something? I'm creating the new post types to differentiate them and use different HTML in each type and, as far as I've been able to tell you can't style posts based on categories.

**Comment by digitalcraftsman** [comment]
Hello @caraya,

this is an interesting point. In mostly all of my themes I use the `post` content type as default. However, this can be quite limiting if someone like you wants to use different content types.

To make things more flexible it would be grea to have a way to let the user decide in the config file which files should be included in the pagination. A simple array of strings should work fine. Now, I only need to find a way to merge all posts of wished content types. 

I'll ask the fine folks at the [Hugo forum](http://discuss.gohugo.io). I search for a way that's both elegant and flexible (for you) at the same time.

**Comment by digitalcraftsman** [comment]
You can find the corresponding discussion [here](https://discuss.gohugo.io/t/including-content-types-dynamically-in-pagination/2593?u=digitalcraftsman).

**Comment by digitalcraftsman** [comment]
The solution to this problem might come a bit late. But Hugo lately introduced `.Site.Params.mainSections` (see spf13/hugo#3206): a way to specify which types of pages are most important ones. Note that this feature is undocumented at the time I'm writing this. By default the list is filled with the section that has the most regular pages. But of couse you can specify your own sections.

In the upcoming version of this theme I'm using this variable to show all posts that are in one of the main sections. See 0928ac7. Stay tuned.
