### ISSUE TITLE
social.html partial does not select correct CSS font awesome class for Google+

### ISSUE THREAD

**Issue by omeganot** [digitalcraftsman/hugo-icarus-theme#25]
class should be "fa fa-google-plus", not "fa fa-googleplus"

**Comment by digitalcraftsman** [comment]
Hi @omeganot,

thanks for reporting this issue. I fixed the CSS class for the Google+ icon in the latest commit.

**Comment by omeganot** [comment]
That's great to hear.  Thanks much for the fix, and even more for the amazing theme!
