### ISSUE TITLE
Support for custom pages

### ISSUE THREAD

**Issue by mmrath** [digitalcraftsman/hugo-icarus-theme#29]
It would be nice to have support for custom pages like say a page for disclaimer or about me. This page should not have discuss enabled and may be not even the side bars

**Comment by digitalcraftsman** [comment]
Hi @mmrath,

I've added all three options to the theme. You can disable the comments, the profile and widgets per page seperately in the frontmatter. Take a look in the frontmatter for more information. The docs have been updated too.

Let me know if you are missing something.

Cheers,
Digitalcraftsman
