### ISSUE TITLE
"hugo server" command

### ISSUE THREAD

**Issue by ghost** [digitalcraftsman/hugo-icarus-theme#34]
Newbie question here. When I do "hugo server" command, the page I see has all the features of your Icarus theme, except for that I can't see the posts on the "home" page [I copied those posts from your "example" folder to the the root (content/post/) folder]. 

So in effect there is nothing published in the middle of the "Home" page. When I click on the links on top, such as "Tags" or "Categories", it correctly takes me to those posts, but not on "Home".  

I think maybe I need to change the "front matter" in your "example" posts that I copied in my root folder, but I am not sure what exactly. Or is is something I need to change in the Themes folder or the "configtoml" files? 

Any idea what I am doing wrong?

Bruno

**Comment by digitalcraftsman** [comment]
Hello @monkeysandwine,

ad hoc I wasn't able to recreate this issue. Would it be possible to share your current setup with me? This could help to trace the error.

**Comment by ghost** [comment]
Of course. I have a Mac OSX El Capitan. I am not sure if I am giving the right info, so here is the file tree:

tree -a
.
├── archetypes
├── config.toml
├── content
│   ├── creating-a-new-theme.md
│   ├── go-is-for-lovers.md
│   ├── hugo-is-for-lovers.md
│   ├── introducing-icarus-and-its-features.md
│   ├── linked-post.md
│   └── migrate-from-jekyll.md
├── data
│   └── l10n.toml
├── layouts
├── static
│   └── banners
│       └── placeholder.png
└── themes
    └── hugo-icarus-theme
        ├── .DS_Store
        ├── .git
        │   ├── HEAD
        │   ├── branches
        │   ├── config
        │   ├── description
        │   ├── hooks
        │   │   ├── applypatch-msg.sample
        │   │   ├── commit-msg.sample
        │   │   ├── post-update.sample
        │   │   ├── pre-applypatch.sample
        │   │   ├── pre-commit.sample
        │   │   ├── pre-push.sample
        │   │   ├── pre-rebase.sample
        │   │   ├── prepare-commit-msg.sample
        │   │   └── update.sample
        │   ├── index
        │   ├── info
        │   │   └── exclude
        │   ├── logs
        │   │   ├── HEAD
        │   │   └── refs
        │   │       ├── heads
        │   │       │   └── master
        │   │       └── remotes
        │   │           └── origin
        │   │               └── HEAD
        │   ├── objects
        │   │   ├── info
        │   │   └── pack
        │   │       ├── pack-1d5d149658a0101c56779d251c4a4f2320963173.idx
        │   │       └── pack-1d5d149658a0101c56779d251c4a4f2320963173.pack
        │   ├── packed-refs
        │   └── refs
        │       ├── heads
        │       │   └── master
        │       ├── remotes
        │       │   └── origin
        │       │       └── HEAD
        │       └── tags
        ├── CHANGELOG.md
        ├── LICENSE.md
        ├── README.md
        ├── archetypes
        │   └── default.md
        ├── images
        │   ├── screenshot.png
        │   └── tn.png
        ├── layouts
        │   ├── 404.html
        │   ├── _default
        │   │   ├── list.html
        │   │   ├── single.html
        │   │   ├── summary.html
        │   │   └── terms.html
        │   ├── index.html
        │   ├── partials
        │   │   ├── article_footer.html
        │   │   ├── article_header.html
        │   │   ├── article_list.html
        │   │   ├── footer.html
        │   │   ├── footer_custom_js.html
        │   │   ├── footer_js.html
        │   │   ├── head.html
        │   │   ├── head_custom.html
        │   │   ├── header.html
        │   │   ├── pagination.html
        │   │   ├── prev_next_post.html
        │   │   ├── profile.html
        │   │   ├── sidebar.html
        │   │   ├── single_article.html
        │   │   ├── social.html
        │   │   └── widgets
        │   │       ├── categories.html
        │   │       ├── recent_articles.html
        │   │       ├── tag_cloud.html
        │   │       └── tags.html
        │   └── shortcodes
        │       ├── gallery.html
        │       └── jsfiddle.html
        ├── static
        │   ├── apple-touch-icon.png
        │   ├── css
        │   │   ├── font-awesome.min.css
        │   │   ├── images
        │   │   │   ├── avatar.png
        │   │   │   ├── logo.png
        │   │   │   └── thumb-default-small.png
        │   │   ├── monokai.css
        │   │   └── style.css
        │   ├── fancybox
        │   │   ├── blank.gif
        │   │   ├── fancybox_loading.gif
        │   │   ├── fancybox_loading@2x.gif
        │   │   ├── fancybox_overlay.png
        │   │   ├── fancybox_sprite.png
        │   │   ├── fancybox_sprite@2x.png
        │   │   ├── helpers
        │   │   │   ├── fancybox_buttons.png
        │   │   │   ├── jquery.fancybox-buttons.css
        │   │   │   ├── jquery.fancybox-buttons.js
        │   │   │   ├── jquery.fancybox-media.js
        │   │   │   ├── jquery.fancybox-thumbs.css
        │   │   │   └── jquery.fancybox-thumbs.js
        │   │   ├── jquery.fancybox.css
        │   │   ├── jquery.fancybox.js
        │   │   └── jquery.fancybox.pack.js
        │   ├── favicon.ico
        │   ├── font-awesome
        │   │   ├── css
        │   │   │   └── font-awesome.min.css
        │   │   └── fonts
        │   │       ├── FontAwesome.otf
        │   │       ├── fontawesome-webfont.eot
        │   │       ├── fontawesome-webfont.svg
        │   │       ├── fontawesome-webfont.ttf
        │   │       ├── fontawesome-webfont.woff
        │   │       └── fontawesome-webfont.woff2
        │   ├── fonts
        │   │   ├── FontAwesome.otf
        │   │   ├── fontawesome-webfont.eot
        │   │   ├── fontawesome-webfont.svg
        │   │   ├── fontawesome-webfont.ttf
        │   │   ├── fontawesome-webfont.woff
        │   │   └── fontawesome-webfont.woff2
        │   └── js
        │       └── script.js
        └── theme.toml

42 directories, 103 files

I have not changed the config.toml file copied to the root directory from your theme except for the shortnames (disqus, google analytics, etc.). I also copied the theme l10n.toml to the root data folder. Should I copy an index file to the root content file?
Bruno

**Comment by ghost** [comment]
Oh! This ERROR below might be a clue to the issue:

**human:mawdev human2$ hugo serve**
Started building site
0 draft content
0 future content
6 pages created
0 non-page files copied
13 paginator pages created
7 tags created
5 categories created
in 96 ms
ERROR: 2016/06/14 15:02:16 hugo.go:637: Walker:  lstat /Users/human2/mawdev/static: no such file or directory
Watching for changes in /Users/human2/mawdev/{data,content,layouts,themes}
ERROR: 2016/06/14 15:02:16 hugo.go:637: Walker:  lstat /Users/human2/mawdev/static: no such file or directory
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

**Comment by ghost** [comment]
Am I missing the "static" folder in my root folder? Should I copy it from somewhere?

**Comment by ghost** [comment]
Solved it. I found that I originally did not have a "post" folder in my content folder. I think that was the issue wrt the posts not showing on the home page. 
I am now working on changing the logos/icons in upper left section and the top menu. I am starting today some HTML/CSS/JavaScript online lessons to look deeper in your theme. Maybe some GoLang later.  I'll send you the web address once the site is done. Many thanks for your help!
Bruno

**Comment by digitalcraftsman** [comment]
Glad to hear that it finally worked.
