### ISSUE TITLE
Arrow up showing when page no scrollbar is needed

### ISSUE THREAD

**Issue by StefanFabian** [digitalcraftsman/hugo-icarus-theme#36]
Hey,

love the theme.
However, the nice little up-arrow that should be shown when you scroll down, is always shown if the page doesn't have a scrollbar.
This is mildly annoying. Unfortunately I couldn't find the file where it is added.

Best regards,
Stefan

**Comment by StefanFabian** [comment]
Found it. The arrow itself is in the sidebar. The logic is in the script. I've changed it so that it shows when the page was scrolled down for 200px.

**Comment by digitalcraftsman** [comment]
Hello @StefanFabian,

thanks for the report. I just had to pull the lastest Javascript files from the original theme.
