### ISSUE TITLE
Tags and Categories links

### ISSUE THREAD

**Issue by ghost** [digitalcraftsman/hugo-icarus-theme#41]
I am trying to have the tags and categories with ".html" links when I generate pages with the Icarus theme using Hugo (because I am using Cloudfront on Amazon S3, and it does not resolve for folders and sub-folders - was able to fix headers with uglyurls and [permalinks] post in config.toml). 

For example I now have this:
http:/mysite.com/categories/canada
http://mysite.com/tags/parks

But I would like to have this:
http:/mysite.com/categories/canada.html
http://mysite.com/tags/parks.html

I think I need to configure the "layout/partials/widget/"   files, but I am not sure how. Any ideas?

Cheers,
Bruno

**Comment by digitalcraftsman** [comment]
Hello @monkeysandwine,

have a look at the [`uglyURLs`](https://gohugo.io/extras/urls#pretty-urls) option for the config file:

> If you would like to have what we call “ugly URLs”, e.g. http://example.com/extras/urls.html, you are in luck. Hugo supports the ability to create your entire site with ugly URLs. Simply add uglyurls = true to your site-wide config.toml, or use the --uglyURLs=true flag on the command line.

**Comment by ghost** [comment]
I did add uglyurls = true to my site-wide config.toml file and it did solve the issue for the categories and tags links on the headers, but the tags and categories links generated on the side bar, within the categories and tags pages, and generated for each page near the date stamps do not generate as ".html" but as the following:

http://mysite.com/tags/parks
http:/mysite.com/categories/canada

**Comment by osgav** [comment]
It looks like you might be able to make a simple edit (or a few, I'm unsure) to your template(s) as described in this comment - https://github.com/spf13/hugo/issues/1989#issuecomment-212367257

**Comment by osgav** [comment]
More than 1 reference to be updated it seems.

(the `/` after `{{ . | urlize }}` needs to be changed to `.html`)

```
`/osgav-blog/themes/casper$ grep -R }/ *
Binary file images/screen.png matches
Binary file images/screenshot.png matches
Binary file images/tn.png matches
layouts/page/cover.html:          <span class="post-tag small"><a href="{{ $baseurl }}tags/{{ . | urlize }}/">#{{ . }}</a></span>
layouts/page/single.html:          <span class="post-tag small"><a href="{{ $baseurl }}tags/{{ . | urlize }}/">#{{ . }}</a></span>
layouts/partials/li.html:                <a href="{{$baseurl}}tags/{{ $tag | urlize }}/">#{{ $tag }}</a>,
layouts/_default/single.html:          <span class="post-tag small"><a href="{{ $baseurl }}tags/{{ . | urlize }}/">#{{ . }}</a></span>

```

**Comment by digitalcraftsman** [comment]
In f23e973f7f1891e8c95dbce616944b6dce6e71dc I improved the way how I link pages and assets. This is now done by a template function of Hugo that should take things like uglyurls into account. Please test the latest version of this theme.

**Comment by osgav** [comment]
Oh, @ghost means deleted github account it appears - I don't use this theme so I can't chime in with a confirmation but high5 ✋ for addressing the issue. Casting my unfamiliar eye over your changes (I could only describe my understanding of this level of Hugo blogging as "approaching novice") all that stood out was `layouts/partial/footer.html` but I believe I've just learnt what removing a blank line at the end of a file looks like to github... Perhaps the issue has also been addressed in my hugo theme too, I know I'm at least one version behind the latest...

Regards!
osgav

**Comment by digitalcraftsman** [comment]
Unfortunately the account of the issue creator was deleted and I tried to fix this issue in the commit linked above. Since nobody is chiming in to this discussion with the same problems I'll close it for now.
