### ISSUE TITLE
Question: How to do syntax highlighting?

### ISSUE THREAD

**Issue by rahulrai-in** [digitalcraftsman/hugo-icarus-theme#47]
I want to post code using this template. Does it support syntax highlighting?

**Comment by digitalcraftsman** [comment]
Hello @moonytheloony,

as you can see on the [demo site](http://themes.gohugo.io/theme/hugo-icarus/2015/10/10/introducing-icarus-and-its-features) it does support syntax highlighting.

Either make the programming language explicite with GitHub flavoured Markdown

``````
```toml
+++
disable_profile = true
disable_widgets = true
+++
```
``````

or just indent the code with for spaces.

The theme makes use of [highlight.js](https://highlightjs.org/), which automatically detects the generated code blocks and adds a color scheme to the code.
