### ISSUE TITLE
share box is not showing up

### ISSUE THREAD

**Issue by kalbasit** [digitalcraftsman/hugo-icarus-theme#48]
I just started blogging with Hugo; I followed the setup guide but for some reason, the share button is not working (clicking on it does not show the share box). Compare [my blog](https://kalbas.it/) with [theme demo](http://themes.gohugo.io/theme/hugo-icarus/). I looked all around but I can't find where the `<div id="article-share-box-xxxxxxxxxx">` is coming from.

**Comment by digitalcraftsman** [comment]
Hello @kalbasit,

it's possible that I forgot to add the in 925dc6a06a058a1692c06faa7e3aca9bfda58724. Without the Javascript no share buttons would appear. First, I was confused too and wondered were it was coming from. But a look at the upstream project resolved the issue luckily.

Cheers,
Digitalcraftsman

**Comment by kalbasit** [comment]
Hello @digitalcraftsman,

It works (JS-wise) but the icon is still missing. See https://kalbas.it/

**Comment by digitalcraftsman** [comment]
> It works (JS-wise) but the icon is still missing.

This means a little box pops up if you click on the share link?

I cloned your the [repository](https://github.com/kalbasit/kalbas.it) of your website and ran Hugo's built-in server and the icons of the social networks appear as expected.

```
git clone https://github.com/kalbasit/kalbas.it
cd kalbas.it/site/
hugo server
```

Does the console in the developer tools of the browser give you an error message?

**Comment by kalbasit** [comment]
The JS box does show up correctly yes, but the arrow near the share link is not there. See screenshot below (the arrow between Comments and share).

![screen shot 2016-09-02 at 9 49 36 am](https://cloud.githubusercontent.com/assets/87115/18211470/97c7a924-70f2-11e6-8092-160c36e3693e.png)

**Comment by digitalcraftsman** [comment]
Thank you for the clarification. I thought you meant the icons of the social networks.

I added the share icon in aa2fa43030b80db352d9a0ec175446ca353d2bd9. I hope this finally resolves this issue.

**Comment by kalbasit** [comment]
@digitalcraftsman that fixed it, thanks!
