### ISSUE TITLE
wget --spider fails on example site

### ISSUE THREAD

**Issue by mathuin** [digitalcraftsman/hugo-icarus-theme#49]
I checked out a copy of the theme, changed to the example site directory, checked out another copy of the theme, and started the server.  I then ran wget in spider mode against the server, and it failed.

``` shell
jmt@nala:~$ mkdir pie
jmt@nala:~$ cd pie
jmt@nala:~/pie$ git clone https://github.com/digitalcraftsman/hugo-icarus-theme.git
Cloning into 'hugo-icarus-theme'...
remote: Counting objects: 790, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 790 (delta 0), reused 0 (delta 0), pack-reused 783
Receiving objects: 100% (790/790), 2.30 MiB | 2.33 MiB/s, done.
Resolving deltas: 100% (490/490), done.
Checking connectivity... done.
jmt@nala:~/pie$ cd hugo-icarus-theme/
(master=) jmt@nala:~/pie/hugo-icarus-theme$ cd exampleSite/
(master=) jmt@nala:~/pie/hugo-icarus-theme/exampleSite$ mkdir themes
(master=) jmt@nala:~/pie/hugo-icarus-theme/exampleSite$ cd themes
(master=) jmt@nala:~/pie/hugo-icarus-theme/exampleSite/themes$ !git
git clone https://github.com/digitalcraftsman/hugo-icarus-theme.git
Cloning into 'hugo-icarus-theme'...
remote: Counting objects: 790, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 790 (delta 0), reused 0 (delta 0), pack-reused 783
Receiving objects: 100% (790/790), 2.30 MiB | 1.43 MiB/s, done.
Resolving deltas: 100% (490/490), done.
Checking connectivity... done.
(master=) jmt@nala:~/pie/hugo-icarus-theme/exampleSite/themes$ cd ../..
(master=) jmt@nala:~/pie/hugo-icarus-theme$ cd exampleSite/
(master=) jmt@nala:~/pie/hugo-icarus-theme/exampleSite$ hugo server
0 draft content
0 future content
6 pages created
0 non-page files copied
14 paginator pages created
7 tags created
5 categories created
in 162 ms
Watching for changes in /home/jmt/pie/hugo-icarus-theme/exampleSite/{data,content,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

In another window:

``` shell
jmt@nala:~$ wget --spider -e robots=off -r -p http://localhost:1313
Spider mode enabled. Check if remote file exists.
... many lines of output elided ...
Found 9 broken links.

http://localhost:1313/tags/index.xml
http://localhost:1313/overview/configuration/
http://localhost:1313/overview/installing/
http://localhost:1313/doc/shortcodes/
http://localhost:1313/layout/functions
http://localhost:1313/categories/index.xml
http://localhost:1313/content/front-matter
http://localhost:1313/layout/variables
http://localhost:1313/layout/templates/

FINISHED --2016-09-02 20:56:52--
Total wall clock time: 0.2s
Downloaded: 27 files, 795K in 0.001s (724 MB/s)
jmt@nala:~$ 
```

Normally, I wouldn't care -- but the spider test also fails for me when I try to use this theme in production, with the two "index.xml" files missing.  Help!

**Comment by digitalcraftsman** [comment]
Hello @mathuin,

I did a bit of testing to find the source of the "broken" links. 7 out of the 9 links are created by the demo content. 

I think it was Steve (Hugo's creator) how began to use some Markdown files form the documentation to populate one of the early themes with demo content. This content files point to some locations in the documentation that are not present on our site. Hence the broken links. It's more about to show something to the user. Just replace the demo content with your own.

The remaining two broken point to the rss feed of the tag and category taxonomies. Currently, a bug prevents the generation of a feed in the root of a taxonomy (see spf13/hugo#1724).

**Comment by mathuin** [comment]
Thank you for the quick response!

Is there a way I can disable the RSS functionality entirely until the hugo bug you mentioned is resolved?

**EDIT:**  I should have mentioned which version of Hugo I'm running!  
"Hugo Static Site Generator v0.16-DEV BuildDate: 2016-02-06T09:14:17-08:00" is what I run locally, but I deploy to a container that installs 0.16 from the releases page.

**Comment by digitalcraftsman** [comment]
According to the [configuration options](https://gohugo.io/overview/configuration/) of Hugo the following one should disable RSS globally:

```
disableRSS = true
```

**Comment by mathuin** [comment]
My issue is now resolved.  Thank you!
