### ISSUE TITLE
How to hide a few things?

### ISSUE THREAD

**Issue by 7MinSec** [digitalcraftsman/hugo-icarus-theme#50]
Hi there,

I'm wondering if you can check the attached screenshot and let me know if there's a way to hide the following:
1. The "1 | 0" below the blog title/desc (is that post count?)
2. The RSS feed link/icon
3. The date on any posts marked as pages?

<img width="918" alt="sweetsurrender_info" src="https://cloud.githubusercontent.com/assets/17596787/18413835/fae064a4-777a-11e6-94c1-c6996d914658.png">

Thanks,
Brian

**Comment by ghost** [comment]
You can remove the post count and tags like so:
![removing_social__d88f9af9__ _commits_ _1705___blog_ _gitlab](https://cloud.githubusercontent.com/assets/2176559/21622644/75a5af86-d1b3-11e6-9a4a-1df3a524f481.png)

**Comment by patrickn** [comment]
Instructions about how to remove the "Posts|Tags" have already been suggested above but as an aside, there should be some text underneath the "1 | 0". As there is no text it suggests your i10n.toml file is not being found. Not a problem here if you remove the blocks, but may cause other side effects. Make sure you have _/data/i10n.toml_ present.

To remove the RSS link search and remove the lines containing .RSSLink in the theme.

**Comment by gregasmaximus** [comment]
As of today, you can hide the entire date line by adding `nodateline = true` to the front matter of a particular page.
