### ISSUE TITLE
Import avatar picture from gravatar 

### ISSUE THREAD

**Issue by douglascamata** [digitalcraftsman/hugo-icarus-theme#51]

**Comment by digitalcraftsman** [comment]
I'm not a Gravatar user. Could you give some information of how avatars can be imported?

**Comment by douglascamata** [comment]
@digitalcraftsman hello, you can find instructions on how avatars can be imported here: https://en.gravatar.com/site/implement/. The only thing necessary to "get" an user's avatar should be his email address, if I recall correctly. The service itself was created to avoid uploading the same picture to many websites and having to manage all of them separately.

**Comment by digitalcraftsman** [comment]
This answer comes a bit late but in b6b79b7 I added an option to use Gravatar as an alternative way to add a profile picture. It will be part of the upcoming release of this theme.
