### ISSUE TITLE
Next page link generates uri with double slash '//'

### ISSUE THREAD

**Issue by patrickn** [digitalcraftsman/hugo-icarus-theme#56]
Hi,

Using the Icarus theme with pagination set at the default 10. At the bottom of the page the link generated for the next page is of the form neavey.net//page/1/, note the //. This confuses S3, where my site is hosted and I get a 404. Manually deleting the superfluous / causes the page to load as expected. 

To recreate go to https://neavey.net, scroll to the bottom and click Next.

**Comment by patrickn** [comment]
I have created a pull request that fixes this issue for me. #58

**Comment by digitalcraftsman** [comment]
In f23e973f7f1891e8c95dbce616944b6dce6e71dc I improved the way how I link pages and assets. Could you please test the latest version of the theme and report back if the issues are still present?

Thanks

**Comment by patrickn** [comment]
Fixes it for me, thanks for the update. :-)

**Comment by patrickn** [comment]
Sorry, looks like I spoke too soon. On page 2 I am still getting problems. I have tried changing baseurl to include a trailing slash but still see the following errors. You can see these at https://www.neavey.net/page/2/.

![errors](https://cloud.githubusercontent.com/assets/308155/20466742/918b3d5c-af70-11e6-8cb1-6a9d64684521.jpg)

**Comment by patrickn** [comment]
At first I thought this issue was fixed, then it looked like I still had a problem. Now however I am seeing some strange behaviour from S3. I am uploading new versions of the site to S3 but seeing old versions via a browser (maybe some caching somewhere, cleared browser cache and still get a problem).

I'll close the issue until I can figure out whats going on or have more details.

**Comment by digitalcraftsman** [comment]
Let me know if it is still an issue with the theme.

**Comment by patrickn** [comment]
It is indeed fixed. I thought I was going crazy earlier because I couldn’t work out why I was still getting the problem, then realised that Amazon CloudFront was caching the page so I was seeing the old broken version.

Thanks for sorting it. Great job.
