### ISSUE TITLE
Disqus comments aren't working.

### ISSUE THREAD

**Issue by InderdeepBajwa** [digitalcraftsman/hugo-icarus-theme#57]
Prior information:
baseurl="/"
My website: www.desktopluxury.com

Disqus comments gives an error 

> We were unable to load Disqus. If you are a moderator please see our troubleshooting guide. 

While changing baseurl to my website's name solves the issue, my website renders into text, no css, no beauty of theme. It seems like theme stops working after changing the baseurl while "/" value in baseurl isn't accepted by disqus comments.
Please help me with this issue.

**Comment by patrickn** [comment]
Out of interest, did you try setting baseurl to: http://www.desktopluxury.com/, with trailing /

Just asking because disqus works fine for me.

**Comment by digitalcraftsman** [comment]
Disqus needs the full base url because `/` isn't a unique address. But it seems that I've to improve the way how I link pages and assets so that a base url like `http://www.desktopluxury.com/` still works.

**Comment by digitalcraftsman** [comment]
In f23e973f7f1891e8c95dbce616944b6dce6e71dc I improved the way how I link pages and assets. Could you please test the latest version of the theme and report back if the issues are still present?

**Comment by InderdeepBajwa** [comment]
Hi @digitalcraftsman , the issue has been fixed. Thanks!
