### ISSUE TITLE
Google search box does not pass search query parameter

### ISSUE THREAD

**Issue by dutchiechris** [digitalcraftsman/hugo-icarus-theme#60]
First off, **awesome** theme!  Thanks for your efforts and sharing with the world!!

I noticed that the google search box does not pass the parameter entered in the search query but instead only the site to search:

![image](https://cloud.githubusercontent.com/assets/917241/20475686/43ec353a-afcd-11e6-820f-f6868574e325.png)

gives you this:
![image](https://cloud.githubusercontent.com/assets/917241/20475699/51f0dd66-afcd-11e6-940e-ca177388d425.png)

whereas it would be great it if gave this:
![image](https://cloud.githubusercontent.com/assets/917241/20475715/67717ccc-afcd-11e6-9b94-f11a8919d521.png)

I had a look around the templates but cannot figure out how/where this search box is being generated.  Maybe someone with more skills than me can locate and fix?

Thanks!
Chris

**Comment by dutchiechris** [comment]
Hi @digitalcraftsman 

Any idea on this one?  Thanks!

**Comment by ybizeul** [comment]
It looks like calling q= twice in the URL isn't supported by every browser. I have no problem in Safari for example but your browser seems to filter and only leave the last one.

**Comment by ybizeul** [comment]
I just tested safari, Firefox and chrome on a mac with no issue. Plugin problem?

**Comment by dutchiechris** [comment]
Actually, it looks like the browser is posting two q= pairs but then Google is redirecting and only using one of them:
![image](https://cloud.githubusercontent.com/assets/917241/21115246/a1f505dc-c0b0-11e6-92a5-b37935c28bfa.png)

So instead of q= twice I'd like the query field to be appened to the q=site with +SEARCH like this:

https://www.google.nl/search?q=site:http:%2F%2Fwww.beginswithdata.com%2F+YANN

**Comment by digitalcraftsman** [comment]
In a Google search you can limit the search results by adding the "site:" filter, e.g.

    foo site:www.gohugo.io

The search query is can be added with the `q` parameter in the url, e.g.

    https://www.google.de/search?q=foo

I tried to append `site: {{ .Site.BaseURL }}` to the `q` parameter. But the filter was just overwritten by the actual search query instead of being appended. A quick search revealed that you can use the `sitesearch` parameter in the url instead to build the url as follows:

    https://www.google.de/search?q=foo&sitesearch=www.gohugo.io

**Comment by ybizeul** [comment]
Awesome! I's funny though it looks like browser dependent, some browsers submit q=&q= without issue and google is actually parsing it by doing a space join.

I think it's cleaner now

**Comment by dutchiechris** [comment]
Yes, fix from @digitalcraftsman verified as working.  Thanks!
