### ISSUE TITLE
RSS feed link changes on posts

### ISSUE THREAD

**Issue by ghost** [digitalcraftsman/hugo-icarus-theme#64]
The RSS link in the "social" area should remain constant - instead, it changes when you are reading a post.

**Comment by digitalcraftsman** [comment]
Hello @dsh1705,

in 9e2010b9bdd3102c4939ea26da44ac758009cbf0 I switched to `.Site.RSSLink` which will always link to `example.com/index.xml` and doesn't change if you are reading a page of a section, e.g. posts.

**Comment by ghost** [comment]
Fantastic - works for me - thanks
