### ISSUE TITLE
link to single page does not render

### ISSUE THREAD

**Issue by dutchiechris** [digitalcraftsman/hugo-icarus-theme#67]
I noticed after updating to hugo .18 that my about page broke.

I had a simple entry like this:

```
[[params.menu]]
    before = false
    label  = "About"
    link   = "about/"
```

and then the single page at `content/about/index.md`.  

I read this other [issue on another @digitalcraftsman theme](https://github.com/digitalcraftsman/hugo-cactus-theme/issues/20) and believe the root cause might be the same.  The workaround from @podiki, to have two files index.md and _index.md in that same dir, did work for me here too.

**Comment by digitalcraftsman** [comment]
Hello @dutchiechris,

thanks for getting in touch. For the upcoming release of this theme I added an example for an about page (see 183f569). This addition should solve your problem. Stay tuned.
