### ISSUE TITLE
baseurl used twice?

### ISSUE THREAD

**Issue by suntong** [digitalcraftsman/hugo-icarus-theme#7]
Hi again digitalcraftsman, 

Please take a look at the source of http://suntong.github.io/blogs/. I see

```
  <link href="suntong.github.io/blogs/index.xml" rel="alternate" type="application/rss+xml" title="Sfxpt Blog" />
  <link href="suntong.github.io/blogs/index.xml" rel="feed" type="application/rss+xml" title="Sfxpt Blog" />

<link rel="icon" href="suntong.github.io/blogs/suntong.github.io/blogs/favicon.ico">
<link rel="apple-touch-icon" href="suntong.github.io/blogs/suntong.github.io/blogs//apple-touch-icon.png" />
<link rel="stylesheet" href="suntong.github.io/blogs/suntong.github.io/blogs/css/style.css">
<link rel="stylesheet" href="suntong.github.io/blogs/suntong.github.io/blogs/css/font-awesome.min.css">
<link rel="stylesheet" href="suntong.github.io/blogs/suntong.github.io/blogs/css/monokai.css">
<link rel="stylesheet" href="suntong.github.io/blogs/suntong.github.io/blogs/fancybox/jquery.fancybox.css">
```

I.e., I see the `suntong.github.io/blogs/` has been doubled up, e.g., `<link rel="stylesheet" href="suntong.github.io/blogs/suntong.github.io/blogs/css/style.css">`. What could be the problem? 

I've put my `config.toml` at https://gist.github.com/suntong/2b529ce26099d6f26278. Could you take a look for me please? 

Thanks

**Comment by digitalcraftsman** [comment]
Hello @suntong,

with your posted config I was able to reproduce the issue. Currently, your base url is set to

```
baseurl = "suntong.github.io/blogs/"
```

But it seems that Hugo doesn't like it if you don't specify the protocol that is used to serve the site. However, adding `http://` or `https://` before your baseurl should solve your problem.

```
baseurl = "https://suntong.github.io/blogs/"
```

**Comment by suntong** [comment]
Yep, that solve it nicely. Can't trace where the typo was coming from now. Thanks.
