### ISSUE TITLE
How to utiliize internal templates?

### ISSUE THREAD

**Issue by WorldsEndless** [digitalcraftsman/hugo-icarus-theme#80]
First off, EXCELLENT theme. THank you. 

I noticed that my banner wasn't becoming my Facebook image, which eventually led me to see there are internal templates for the likes of og-graph. If I understand right, these are (maybe?) internal to Hugo, or internal to Go? No amount of searching has led me to any documentation that talks about these, though. Where can I learn about the internal templates, especially for social media?

**Comment by digitalcraftsman** [comment]
Hello @WorldsEndless,

> If I understand right, these are (maybe?) internal to Hugo

You're right. They're built-in to Hugo but currently undocumented (see spf13/hugo#1727). However, you can find the internal templates [here](https://github.com/spf13/hugo/blob/eb27c47fc5102e05945f3beb892a839284d56dc8/tpl/tplimpl/template_embedded.go#L162).

**Comment by digitalcraftsman** [comment]
I'll close this issue since the documentation should be fixed upstream in Hugo.
