### ISSUE TITLE
An empty post with a title 'Posts'

### ISSUE THREAD

**Issue by igor-sokolov** [digitalcraftsman/hugo-icarus-theme#81]
Hi,

I noticed that I can see an additional empty post with a title 'Post' and URL to http://localhost:1313/post/ ' if there is at least one post. The same thing I observe with another theme from your repository 'hugo-minimalist'. I use the last version of Hugo 0.19. I'm absolutely new in Hugo but through comparing with other themes where the issue is not observed I found out that the root of issue is in the line:
{{ $paginator := .Paginate (where .Site.Pages "Type" "post") }}
If it is changed to:
{{ $paginator := .Paginate (where .Data.Pages "Type" "post") }}
then there is a correct number of posts displayed on the home page. To be honest with you I don't know why it's that:-)

Best regards,
Igor.

**Comment by digitalcraftsman** [comment]
Hello @igor-sokolov,

thanks for getting in touch. This issue will be fixed with the upcoming release of this theme. Stay tuned,
