### ISSUE TITLE
MathJax CDN shutting down

### ISSUE THREAD

**Issue by matlipson** [digitalcraftsman/hugo-icarus-theme#87]
As announced here: https://www.mathjax.org/cdn-shutting-down/

MathJax requires update to new CDN. Affects footer_js.html 

Also: 
>Note If you have been using https://cdn.mathjax.org/mathjax/latest/, we suggest to switch to a fixed version going forward as this represents best practices to avoid unexpected changes."

**Comment by digitalcraftsman** [comment]
Hello @matlipson,

thanks for getting in touch. This issue is already fixed by #86 which has been merged on the dev branch. I'll release this fix with the next version of this theme. Stay tuned.
