### ISSUE TITLE
ERROR: Page's Now is deprecated 

### ISSUE THREAD

**Issue by patrickn** [digitalcraftsman/hugo-icarus-theme#96]
The following statement in footer.html:

    {{ now.Format "2006"}}

Causes the following error message:

    ERROR 2017/07/14 10:24:46 Page's Now is deprecated and will be removed in Hugo 0.27. Use now (the template func).

I understand changes were made recently for this deprecation but this issue still persists.

**Comment by digitalcraftsman** [comment]
Hello @patrickn,

which version of Hugo are you using? I've tried v0.25.1 as well as the newest version from master but was unable to reproduce the error message.

**Comment by patrickn** [comment]
I tried with the latest 0.26-DEV I think. Removing the now.Format statement fixes the error. If you can't recreate it, I don't know what it could be. Could it be something in my config?

**Comment by digitalcraftsman** [comment]
Is this issue related to your https://github.com/patrickn/neaveynet-hugo repo?

My guess would be the following: you're [added this theme as a submodule](https://github.com/patrickn/neaveynet-hugo/tree/master/themes) and the referenced commit if from 2016. Therefore, it's possible that you use an old version of the Icarus theme that still uses the deprecated `.Now` template function.

**Comment by patrickn** [comment]
Yes, I think you are correct. Trouble is I am in the road so debugging this from my phone. I thought I had done a submodule update from travis.yaml but it seems it didn't work, or didn't do what I expected. 

I will close the issue and make sure to use the latest Icarus. 

Thank you very much for looking into this. 

Awesome theme by the way. 

Patrick

**Comment by digitalcraftsman** [comment]
Let's hope it will solve the issue you're facing :wink:
